baseurl = "http://blog.2no.me/"
languageCode = "ja"
title = "blog.2no.me"
author = "2no"
disqusShortname = "2no"
publishdir = "docs"

[params]
  logo       = "/images/img.jpg"
  copyright  = "2no All rights reserved."
  twitter    = "https://twitter.com/wakuworks"
  github     = "https://github.com/2no/"
  tagmanager = "GTM-P4B6RC"
